### PR TITLE
Added "Splitfire" and "Vampire shots" bonuses

### PR DESCRIPTION
**Pull request by plesatejvlk**

### CODE REVIEW

**Comment by odanek** [comment]
Thanks ;)

**Comment by plesatejvlk** [comment]
My pleasure.;)

**Comment by odanek** [comment]
There are resources now in the repo so you can update the bonus images if you wish.

**Comment by plesatejvlk** [comment]
I'm on it! ;) Btw, I have revamped all the bonus textures (another pull request coming soon ;) )

**Pull request merged**
